[DOC UPDATE ]Fix ImportError: cannot import name 'ModelFilter' from 'huggingface_hub' in slm_pretraining_sft.ipynb (#208)
latest huggingface_hub with nemo_toolkit==1.23.0 does not have  ModelFilter.